# https://taskfile.dev

version: '3'

tasks:
  dacpac:
    dir: dacpac
    cmds:
      - docker-compose up -d tools
      - cmd: docker-compose exec tools bash -c '/opt/sqlpackage/sqlpackage /a:Extract /scs:"Data Source=host.docker.internal,14331;Initial Catalog={{.DATABASE}};User ID={{.USER}};Password={{.PASS}};" /tf:/tmp/dump/{{.DATABASE}}.dacpac'
        ignore_error: true
      - docker-compose down

    vars:
      DATABASE: main
      USER: sa
      PASS: P@55w0rd
